spring: 
  profiles:
    active:
    - dev
---
spring: 
  profiles: dev  #开发环境
  application:
    name: parent_cloud_01-config-bdqn-dev
---
spring: 
  profiles: test  #测试环境
  application:
    name: parent_cloud_01-config-bdqn-test